spring:
  application:
    name: eureka-server
  profiles:
    active: server1

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health

  endpoint:
    health:
      show-details: always #默认是never