server:
  port: 8763

spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/,http://localhost:20002/eureka/